language: cpp
compiler:
  - gcc
  - clang
install: make deps > /dev/null
script:
  - source /opt/qt53/bin/qt53-env.sh && make clean && make fmt && make lint && make test && make
branches:
  only:
    - master
notifications:
  recipients:
    - tanel.lebedev@gmail.com
  email:
    on_success: change
    on_failure: always
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt531
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt53tools qt53svg qt53webkit libxss-dev xorg-dev
